In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from decisiontree import DecisionTreeModel as DT, accuracy_score, write_dict_to_file
import utils as ut

## Feature -- 1 word before target(1000 samples)

In [6]:
X, y, vocabs_oh = ut.create_dataset("hw1_dataset/hw1.train_mini.col", 1, 'before')
X

,0,1,2,3,4,5,6,7,8,9,...,254,255,256,257,258,259,260,261,262,263
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
977,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
978,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# X[X.duplicated(keep=False)]

In [4]:
model2 = DT()
model2.fit(X,y)

Start fitting

In [5]:
X_dev, y_dev, _ = ut.create_dataset("hw1_dataset/hw1.dev.col", 1, 'before', vocabs_oh)
X_dev

,0,1,2,3,4,5,6,7,8,9,...,254,255,256,257,258,259,260,261,262,263
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
989,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
990,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
991,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
993,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [6]:
y_dev_pred = model2.predict(X_dev)

In [7]:
y_dev_pred = model2.predict(X_dev)
acc = accuracy_score(y_dev, y_dev_pred)
acc

0.7967479674796748

## Feature -- 1 word after target(1000 samples)

In [8]:
X, y, vocabs_oh = ut.create_dataset("hw1_dataset/hw1.train_mini.col", 1, 'after')
X

,0,1,2,3,4,5,6,7,8,9,...,266,267,268,269,270,271,272,273,274,275
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
984,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
model2 = DT()
model2.fit(X,y)

Start fitting

In [10]:
X_dev, y_dev, _ = ut.create_dataset("hw1_dataset/hw1.dev.col", 1, 'after', vocabs_oh)
X_dev

,0,1,2,3,4,5,6,7,8,9,...,266,267,268,269,270,271,272,273,274,275
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
982,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
984,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
y_dev_pred = model2.predict(X_dev)
acc = accuracy_score(y_dev, y_dev_pred)
acc

0.7700729927007299

## Feature -- 1 word before target(5000 samples)

In [2]:
X, y, vocabs_oh = ut.create_dataset("hw1_dataset/hw1.train_mid.col", 1, 'before')
X

,0,1,2,3,4,5,6,7,8,9,...,667,668,669,670,671,672,673,674,675,676
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4964,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4970,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4987,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
model3 = DT()
model3.fit(X, y)

Start fitting

In [4]:
X_dev, y_dev, _ = ut.create_dataset("hw1_dataset/hw1.dev.col", 1, 'before', vocabs_oh)
X_dev

,0,1,2,3,4,5,6,7,8,9,...,667,668,669,670,671,672,673,674,675,676
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
989,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
y_dev_pred = model3.predict(X_dev)
acc = accuracy_score(y_dev, y_dev_pred)
acc

0.7479674796747967

## Feature -- 1 word before + after target(5000 samples)

In [2]:
X, y, vocabs_oh = ut.create_dataset("hw1_dataset/hw1.train_mini.col", 1)
X

,0,1,2,3,4,5,6,7,8,9,...,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
model4 = DT()
model4.fit(X,y)

Start fitting

In [4]:
X_dev, y_dev, _ = ut.create_dataset("hw1_dataset/hw1.dev.col", 1, 'both', vocabs_oh)
X_dev

,0,1,2,3,4,5,6,7,8,9,...,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
y_dev_pred = model4.predict(X_dev)
acc = accuracy_score(y_dev, y_dev_pred)
acc

0.904891304347826

In [ ]:
X_test, y_test, _ = ut.create_dataset("hw1_dataset/hw1.test.col", 1, 'before', vocabs_oh)
X_test

In [ ]:
X_dev, y_dev, _ = ut.create_dataset("hw1_dataset/hw1.dev.col", 1, 'before', vocabs_oh)
X_dev

In [ ]:
model1 = DT()

In [ ]:
X

In [ ]:
y.shape

In [ ]:
model1.fit(X,y)

In [ ]:
y_dev_pred = model1.predict(X_dev_test)

In [ ]:
acc = accuracy_score(y_dev, y_dev_pred)

In [ ]:
model2.fit(X_micro,y_micro)

In [ ]:
y_pred = model2.predict(X_test)

In [ ]:
y_test = y_test['Target']

In [ ]:
acc = accuracy_score(y_test, y_pred)

In [ ]:
acc