In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from decisiontree import DecisionTreeModel as DT, accuracy_score, write_dict_to_file
import utils as ut

In [ ]:
X_train = pd.read_csv('X_train_range2.csv')
y_train = pd.read_csv('y_train_range2.csv')

In [ ]:
X_dev = pd.read_csv('X_dev_range2.csv')
y_dev = pd.read_csv('y_dev_range2.csv')['Target']

In [ ]:
X_test = pd.read_csv('X_test_range2.csv')
y_test = pd.read_csv('y_test_range2.csv')['Target']

In [ ]:
model1 = DT()

In [ ]:
model1.fit(X_train,y_train)

In [ ]:
y_dev_pred = model1.predict(X_dev)

In [ ]:
acc = accuracy_score(y_dev, y_dev_pred)
acc

In [ ]:
# def accuracy_score(y_true, y_pred):
#     accuracy = np.sum(y_true == y_pred) / len(y_true)
#     return accuracy

In [ ]:
# y_test = y_test['Target']

## Feature -- 1 previous word

In [2]:
X, y, vocabs_oh = ut.create_dataset("hw1_dataset/hw1.train.col", 1, 'before')
# X, y, vocabs_oh = _create_dataset("Ying_wordTest.csv", 1, 'before')
X

,0,1,2,3,4,5,6,7,8,9,...,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17545,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17546,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17547,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
17548,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17549,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
X_test, y_test, _ = ut.create_dataset("hw1_dataset/hw1.test.col", 1, 'before', vocabs_oh)
X_test

,0,1,2,3,4,5,6,7,8,9,...,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
X_dev, y_dev, _ = ut.create_dataset("hw1_dataset/hw1.dev.col", 1, 'before', vocabs_oh)
X_dev

,0,1,2,3,4,5,6,7,8,9,...,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
model1 = DT()

In [ ]:
model1.fit(X,y)

Start fitting

In [ ]:
y_dev_pred = model1.predict(X_dev_test)

In [ ]:
acc = accuracy_score(y_dev, y_dev_pred)

In [ ]:
model2.fit(X_micro,y_micro)

In [ ]:
y_pred = model2.predict(X_test)

In [ ]:
y_test = y_test['Target']

In [ ]:
acc = accuracy_score(y_test, y_pred)

In [ ]:
acc