In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from decisiontree import DecisionTreeModel as DT, accuracy_score, write_dict_to_file
import utils as ut

## Feature -- 1 word before target(5000 samples)

In [2]:
X, y, vocabs_oh = ut.create_dataset("hw1_dataset/hw1.train_mid_rnd.col", 1, 'before')
X

,0,1,2,3,4,5,6,7,8,9,...,653,654,655,656,657,658,659,660,661,662
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4934,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4938,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4942,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4957,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4969,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
model1 = DT()
model1.fit(X, y)

Start fitting

In [4]:
X_dev, y_dev, _ = ut.create_dataset("hw1_dataset/hw1.dev.col", 1, 'before', vocabs_oh)
X_dev

,0,1,2,3,4,5,6,7,8,9,...,653,654,655,656,657,658,659,660,661,662
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
989,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
y_dev_pred = model1.predict(X_dev)
acc = accuracy_score(y_dev, y_dev_pred)
acc

0.7560975609756098

## Feature -- 1 word after target(5000 samples)

In [6]:
X, y, vocabs_oh = ut.create_dataset("hw1_dataset/hw1.train_mid_rnd.col", 1, 'after')
X

,0,1,2,3,4,5,6,7,8,9,...,987,988,989,990,991,992,993,994,995,996
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4982,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
model2 = DT()
model2.fit(X, y)

Start fitting

In [8]:
X_dev, y_dev, _ = ut.create_dataset("hw1_dataset/hw1.dev.col", 1, 'after', vocabs_oh)
X_dev

,0,1,2,3,4,5,6,7,8,9,...,987,988,989,990,991,992,993,994,995,996
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
982,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
984,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
y_dev_pred = model2.predict(X_dev)
acc = accuracy_score(y_dev, y_dev_pred)
acc

0.7518248175182481

## Feature -- 1 word before + after target(5000 samples)

In [11]:
X, y, vocabs_oh = ut.create_dataset("hw1_dataset/hw1.train_mid_rnd.col", 1)
X

,0,1,2,3,4,5,6,7,8,9,...,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [12]:
model3 = DT()
model3.fit(X,y)

Start fitting

In [13]:
X_dev, y_dev, _ = ut.create_dataset("hw1_dataset/hw1.dev.col", 1, 'both', vocabs_oh)
X_dev

,0,1,2,3,4,5,6,7,8,9,...,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
y_dev_pred = model3.predict(X_dev)
acc = accuracy_score(y_dev, y_dev_pred)
acc

0.9293478260869565

## Model3 (1 word before + after target) on Test Dataset

In [21]:
X_test, y_test, _ = ut.create_dataset("hw1_dataset/hw1.test.col", 1, 'both', vocabs_oh)
X_test

,0,1,2,3,4,5,6,7,8,9,...,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
y_test_pred = model3.predict(X_test)
acc = accuracy_score(y_test, y_test_pred)
acc

0.9215686274509803

## Limit Hight to 10 (5000 samples) - 1 word before + after target

In [15]:
model4 = DT(max_depth=10)
model4.fit(X,y)

Start fitting

In [23]:
y_test_pred = model4.predict(X_test)

In [24]:
acc = accuracy_score(y_test, y_test_pred)
acc

0.8753501400560224

## Limit Hight to 3 (5000 samples) - 1 word before + after target

In [19]:
model5 = DT(max_depth=3)
model5.fit(X,y)

Start fitting

In [25]:
y_test_pred = model5.predict(X_test)
acc = accuracy_score(y_test, y_test_pred)
acc

0.8389355742296919

In [ ]:
y_dev_pred = model1.predict(X_dev_test)

In [ ]:
acc = accuracy_score(y_dev, y_dev_pred)

In [ ]:
model2.fit(X_micro,y_micro)

In [ ]:
y_pred = model2.predict(X_test)

In [ ]:
y_test = y_test['Target']

In [ ]:
acc = accuracy_score(y_test, y_pred)

In [ ]:
acc